### ISSUE TITLE
Fresnel reflections

### ISSUE THREAD

**Issue by marijnhurkens** [bheisler/raytracer#3]
Hi,

I'm trying to implement my own toy ray tracer in Rust, but I am having lot's of trouble with the Fresnel calculations. Out of frustration I just tried to just copy your fresnel function, but I only get 0.04 or 0.03999999 as a result. I isolated the function and wrote some tests but I am unable to get the function to work correctly. Can you help me?

I copied this function:
https://github.com/bheisler/raytracer/blob/master/src/rendering.rs#L267-L287

The test results for a 0 degree angle are correct (I think 0.04 is correct when the IOR = 1.5). I also test a 90 degree angle and smaller angles, but the result stays around 0.04.

```
---- helpers::tests::test_fresnel_ratio_half_at_around_80_deg_on_normal stdout ----
Normal Vector3 [0.0, 0.0, -1.0]
 Angle of incidence: Vector3 [1.0, 0.0, 0.2]
ior: 1.5
ratio: 0.04000000000000001
0.04000000000000001
thread 'helpers::tests::test_fresnel_ratio_half_at_around_80_deg_on_normal' panicked at 'assertion failed: ratio > 0.499999', src\helpers.rs:184:9
note: Run with `RUST_BACKTRACE=1` for a backtrace.

---- helpers::tests::test_fresnel_ratio_one_at_perpendicular_of_normal stdout ----
Normal Vector3 [0.0, 0.0, -1.0]
 Angle of incidence: Vector3 [1.0, 0.0, 0.0]
ior: 1.5
ratio: 0.040000000000000015
0.040000000000000015
thread 'helpers::tests::test_fresnel_ratio_one_at_perpendicular_of_normal' panicked at 'assertion failed: ratio > 0.99999999', src\helpers.rs:171:9
```

Any ideas?

Edit:

I also tried the following. With this code I got values between 1 and 1000 or more...

```rust
let mut n1 = 1.0;
    let mut n2 = ior;

    let cos_theta_incidence = normal_normalized.dot(angle_of_incidence_normalized);
    let sin_theta_incidence = (1.0 - cos_theta_incidence * cos_theta_incidence).sqrt();

    if cos_theta_incidence > 0.0 {
        n1 = ior;
        n2 = 1.0;
    }

    let sin_theta_transmittance = n1 * (sin_theta_incidence / n2);
    let cos_theta_transmittance = (1.0 - sin_theta_transmittance * sin_theta_transmittance).sqrt();

    let n1_cos_theta_transmittance = n1 * cos_theta_transmittance;
    let n2_cos_theta_transmittance = n2 * cos_theta_transmittance;
    let n1_cos_theta_incidence = n1 * cos_theta_incidence;
    let n2_cos_theta_incidence = n2 * cos_theta_incidence;

    let s_polarized_sqrt = (n1_cos_theta_incidence - n2_cos_theta_transmittance)
        / (n1_cos_theta_incidence + n2_cos_theta_transmittance);
    let s_polarized = s_polarized_sqrt * s_polarized_sqrt;

    let p_polarized_sqrt = (n2_cos_theta_incidence - n1_cos_theta_transmittance)
        / (n2_cos_theta_incidence + n1_cos_theta_transmittance);
    let p_polarized = p_polarized_sqrt * p_polarized_sqrt;

    fresnel_ratio = (s_polarized + p_polarized) / 2.0;
```

**Comment by bheisler** [comment]
Huh. I see that as well. It's very possible my code is wrong. Unfortunately, it's been quite some time since I really looked at that (and I foolishly didn't write any unit tests of my own) so I have no idea what might be wrong with it or how to fix it.

Sorry I couldn't help more.

**Comment by marijnhurkens** [comment]
Thanks for taking the time!

I fixed it for now by looking up a Fresnel function in the Povray sourcecode, which seems to work fine. 

```rust
    let fresnel_ratio: f64;

    // FROM POVRAY
    // https://github.com/POV-Ray/povray/blob/master/source/core/render/trace.cpp#L2668

    let cos_theta_incidence = normal.dot(angle_of_incidence).abs();
    let sqrg = ior * ior + cos_theta_incidence * cos_theta_incidence - 1.0;

    if sqrg <= 0.0 {
        fresnel_ratio = 1.0;
    } else {
        let g = sqrg.sqrt();
        let quot1 = (g - cos_theta_incidence) / (g + cos_theta_incidence);
        let quot2 = (cos_theta_incidence * (g + cos_theta_incidence) - 1.0)
            / (cos_theta_incidence * (g - cos_theta_incidence) + 1.0);

        let mut f = 0.5 * (quot1 * quot1) * (1.0 + (quot2 * quot2));

        if f > 1.0 {
            f = 1.0;
        }

        if f < 0.0 {
            f = 0.0;
        }

        fresnel_ratio = f;
    }

    fresnel_ratio
```
